"""
database.py
-----------
SQLAlchemy models and session management for the chatbot's PostgreSQL store.

Two tables are defined:
- ``chat_messages``: every user/AI message exchange, optionally linked to a
  Pinecone vector via ``vector_id``.
- ``memory_contexts``: extracted facts about a user (preferences, beliefs,
  decisions) with a confidence score, also optionally linked to Pinecone.

``DATABASE_URL`` is read from the environment so the same code works locally
(SQLite or a local Postgres instance) and inside Docker (injected by
docker-compose from the root ``.env`` file).

Usage
-----
Import ``get_db`` as a FastAPI dependency to obtain a scoped session::

    from database import get_db
    from fastapi import Depends
    from sqlalchemy.orm import Session

    @app.get("/example")
    def example(db: Session = Depends(get_db)):
        ...

Call ``init_db()`` once at application startup to create all tables.
"""

import os

from dotenv import load_dotenv

load_dotenv()

from datetime import datetime

from sqlalchemy import Column, DateTime, Float, String, Text, create_engine
from sqlalchemy.orm import DeclarativeBase, sessionmaker

DATABASE_URL = os.getenv(
    "DATABASE_URL", "postgresql://ai_user:ai_pass@localhost:5432/personal_ai"
)

engine = create_engine(
    DATABASE_URL,
    pool_size=5,
    max_overflow=10,
    pool_pre_ping=True,  # reconnect automatically after DB restarts
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass


class ChatMessage(Base):
    """Persisted record of a single user/AI message exchange.

    Attributes:
        id: UUID v4 string; primary key generated by the application.
        session_id: Browser-generated UUID that groups messages belonging to
            the same conversation; indexed for fast lookups.
        message: The raw text sent by the user.
        response: The AI-generated reply.
        timestamp: UTC datetime when the exchange was stored.
        vector_id: ID of the corresponding vector in Pinecone, or an empty
            string when Pinecone is unavailable.
    """

    __tablename__ = "chat_messages"

    id = Column(String, primary_key=True)
    session_id = Column(String, index=True)
    message = Column(Text)
    response = Column(Text)
    timestamp = Column(DateTime, default=datetime.utcnow)
    vector_id = Column(String, nullable=True)  # Reference to Pinecone vector


class MemoryContext(Base):
    """An extracted fact or preference about the user within a session.

    Memory contexts are generated from chat messages when the system detects
    that the user expressed a preference, belief, or decision.  They are
    stored in both PostgreSQL (for reliable retrieval) and Pinecone (for
    semantic similarity search).

    Attributes:
        id: UUID v4 string; primary key generated by the application.
        session_id: UUID linking this memory to a specific conversation
            session; indexed for fast lookups.
        content: Human-readable description of the memory
            (e.g. "User prefers Python for backend work").
        memory_type: Category string — one of ``preference``, ``belief``,
            or ``decision``.
        confidence: Float in ``[0.0, 1.0]`` representing how certain the
            system is about this memory.  Values ≥ 0.7 are used for context
            injection.
        timestamp: UTC datetime when the memory was stored.
        vector_id: ID of the corresponding vector in Pinecone, or an empty
            string when Pinecone is unavailable.
    """

    __tablename__ = "memory_contexts"

    id = Column(String, primary_key=True)
    session_id = Column(String, index=True)
    content = Column(Text)
    memory_type = Column(String)  # preference, belief, decision
    confidence = Column(Float)
    timestamp = Column(DateTime, default=datetime.utcnow)
    vector_id = Column(String, nullable=True)


def init_db():
    """Run Alembic migrations to bring the database schema up to date.

    Uses ``alembic upgrade head`` programmatically so the app always starts
    with the latest schema.  Falls back to ``create_all`` if Alembic is not
    available (e.g. in lightweight test environments).
    """
    try:
        import os

        from alembic import command
        from alembic.config import Config

        alembic_cfg = Config(os.path.join(os.path.dirname(__file__), "alembic.ini"))
        command.upgrade(alembic_cfg, "head")
    except Exception:
        # Fallback for test environments that don't have a full Alembic setup
        Base.metadata.create_all(bind=engine)


def get_db():
    """FastAPI dependency that yields a scoped SQLAlchemy session.

    Ensures the session is always closed after the request completes,
    even if an exception is raised.

    Yields:
        Session: An active SQLAlchemy ``Session`` bound to the configured
            PostgreSQL (or SQLite) database.
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
