"""
schemas.py
----------
Pydantic request and response models for the chatbot API.

These models are used by FastAPI for automatic request validation,
serialisation, and OpenAPI schema generation (visible at ``/docs``).

Models
------
- :class:`ChatRequest` — body for ``POST /chat``
- :class:`MemorySuggestion` — a single memory hint embedded in chat responses
- :class:`ChatResponse` — response body for ``POST /chat``
- :class:`SessionSummary` — a brief summary of one chat session
- :class:`ChatHistoryMessage` — a single message in a chat history response
"""

from datetime import datetime

from pydantic import BaseModel, Field, field_validator


class ChatRequest(BaseModel):
    """Request body for the ``POST /chat`` endpoint.

    Attributes:
        message: The text message sent by the user (1–4000 characters).
        session_id: UUID v4 string that identifies the conversation session.
            Generated by the frontend on first load and stored in
            ``localStorage`` so it persists across page refreshes.
    """

    message: str = Field(..., min_length=1, max_length=4000)
    session_id: str = Field(..., min_length=1, max_length=128)

    @field_validator("message")
    @classmethod
    def message_not_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("message must not be blank")
        return v


class MemorySuggestion(BaseModel):
    """A memory hint detected during a chat exchange.

    The backend analyses each user message and may surface zero or more
    suggestions indicating that a piece of information is worth remembering.
    The frontend can use these to prompt the user or automatically store them
    via ``POST /memory``.

    Attributes:
        type: Category of memory — one of ``"preference"``, ``"belief"``, or
            ``"decision"``.
        content: Short human-readable description of the detected memory.
        confidence: How confident the system is, as a float in ``[0.0, 1.0]``.
        context: Optional free-text explaining why this suggestion was raised.
    """

    type: str  # "preference", "belief", "decision"
    content: str
    confidence: float  # 0.0 to 1.0
    context: str | None = None


class ChatResponse(BaseModel):
    """Response body for the ``POST /chat`` endpoint.

    Attributes:
        reply: The AI-generated response to the user's message.
        memory_suggestions: Zero or more memory hints detected from the
            current message.  Empty list when no patterns were found.
    """

    reply: str
    memory_suggestions: list[MemorySuggestion] = []


class SessionSummary(BaseModel):
    """A brief summary of a single chat session, used in the sessions list.

    Attributes:
        session_id: UUID v4 string identifying the session.
        title: Truncated first user message used as a display title.
        preview: Snippet of the most recent AI response.
        message_count: Total number of exchanges stored for this session.
        last_message_at: UTC timestamp of the most recent exchange.
    """

    session_id: str
    title: str
    preview: str
    message_count: int
    last_message_at: datetime


class ChatHistoryMessage(BaseModel):
    """A single message entry returned by the full history endpoint.

    Attributes:
        id: UUID of the ``ChatMessage`` row.
        role: Either ``"user"`` or ``"ai"``.
        content: The text of the message.
        timestamp: UTC datetime when the exchange was stored.
    """

    id: str
    role: str  # "user" or "ai"
    content: str
    timestamp: datetime
