"""
schemas.py
----------
Pydantic request and response models for the chatbot API.

These models are used by FastAPI for automatic request validation,
serialisation, and OpenAPI schema generation (visible at ``/docs``).

Models
------
- :class:`ChatRequest` — body for ``POST /chat``
- :class:`MemorySuggestion` — a single memory hint embedded in chat responses
- :class:`ChatResponse` — response body for ``POST /chat``
"""

from pydantic import BaseModel, Field
from typing import List, Optional

class ChatRequest(BaseModel):
    """Request body for the ``POST /chat`` endpoint.

    Attributes:
        message: The text message sent by the user.
        session_id: UUID v4 string that identifies the conversation session.
            Generated by the frontend on first load and stored in
            ``localStorage`` so it persists across page refreshes.
    """

    message: str
    session_id: str  # UUID v4 string

class MemorySuggestion(BaseModel):
    """A memory hint detected during a chat exchange.

    The backend analyses each user message and may surface zero or more
    suggestions indicating that a piece of information is worth remembering.
    The frontend can use these to prompt the user or automatically store them
    via ``POST /memory``.

    Attributes:
        type: Category of memory — one of ``"preference"``, ``"belief"``, or
            ``"decision"``.
        content: Short human-readable description of the detected memory.
        confidence: How confident the system is, as a float in ``[0.0, 1.0]``.
        context: Optional free-text explaining why this suggestion was raised.
    """

    type: str  # "preference", "belief", "decision"
    content: str
    confidence: float  # 0.0 to 1.0
    context: Optional[str] = None

class ChatResponse(BaseModel):
    """Response body for the ``POST /chat`` endpoint.

    Attributes:
        reply: The AI-generated response to the user's message.
        memory_suggestions: Zero or more memory hints detected from the
            current message.  Empty list when no patterns were found.
    """

    reply: str
    memory_suggestions: List[MemorySuggestion] = []
